---
ID: "86eaa574-1af8-4562-a6e1-a158fb21ddbd"
Parent: "49a27dc8-2a6a-48a2-a8ef-02a3dd0d3274"
Template: "49a27dc8-2a6a-48a2-a8ef-02a3dd0d3274"
Path: /sitecore/templates/Modules/Sitecron/SiteCron Run As Sitecore Job/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T184925Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8d9bf9d3-9589-4749-a32e-5e04f7ca0f1f"
      Hint: SitecoreJobType
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T184925Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8d9bf9d3-9589-4749-a32e-5e04f7ca0f1f"
      Hint: SitecoreJobType
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
