---
ID: "835c3a2d-15d7-4db2-a3da-e6580a84f9ea"
Parent: "7f2c8881-6ae4-48cf-a499-7745cc4b2eb2"
Template: "7f2c8881-6ae4-48cf-a499-7745cc4b2eb2"
Path: /sitecore/templates/Modules/Sitecron/Sitecron Job/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150620T160601
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150620T160601
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
