---
ID: "30877fd5-1c5c-46d4-930c-1fe23058eba8"
Parent: "b9b437b2-789c-48f6-aae2-b49c4aa2a4bb"
Template: "b9b437b2-789c-48f6-aae2-b49c4aa2a4bb"
Path: /sitecore/templates/Modules/Sitecron/SiteCron Sitecore Schedule Command Job/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T185103Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.SitecoreScheduleCommandJob, Sitecron
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T185103Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.SitecoreScheduleCommandJob, Sitecron
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
